import { defineType, defineField } from 'sanity';

export const product = defineType({
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      description: 'Add one or more lines. Multiple lines are shown as bullet points on the product page.',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'price',
      title: 'Price',
      type: 'number',
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: 'originalPrice',
      title: 'Original Price',
      type: 'number',
      description: 'Used to show a discount (strikethrough price).',
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{ type: 'category' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'images',
      title: 'Images',
      type: 'array',
      of: [{ type: 'image', options: { hotspot: true } }],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'sizes',
      title: 'Sizes',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'XXS', value: 'XXS' },
          { title: 'XS', value: 'XS' },
          { title: 'S', value: 'S' },
          { title: 'M', value: 'M' },
          { title: 'L', value: 'L' },
          { title: 'XL', value: 'XL' },
          { title: 'XXL', value: 'XXL' },
        ],
      },
    }),
    defineField({
      name: 'colors',
      title: 'Colors',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'newArrival',
      title: 'New Arrival',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'bestSeller',
      title: 'Best Seller',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'itemCode',
      title: 'Item Code',
      type: 'string',
    }),
    defineField({
      name: 'stock',
      title: 'Stock Quantity',
      type: 'number',
      initialValue: 0,
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: 'modelDetails',
      title: 'Model Details',
      type: 'string',
      description: 'e.g. "Model is 5\'9" and wearing size M"',
    }),
    defineField({
      name: 'material',
      title: 'Material',
      description: 'e.g. "100% Premium Cotton" or "80% Cotton, 20% Polyester"',
      type: 'string',
    }),
    defineField({
      name: 'careInstructions',
      title: 'Care Instructions',
      description: 'Add each care instruction as a separate item — they will appear as bullet points.',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'styleGuide',
      title: 'Style Guide',
      description: 'Styling tips for this product. Each item becomes a bullet point.',
      type: 'array',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'shippingInfo',
      title: 'Shipping & Returns',
      description: 'Shipping and returns info. Each item becomes a bullet point.',
      type: 'array',
      of: [{ type: 'string' }],
    }),
  ],
});
